// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbjltvwgrhgrcthmkiwo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRiamx0dndncmhncmN0aG1raXdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMDM2NzcsImV4cCI6MjA2ODU3OTY3N30.fxLEL_LfxX9plvLi9A1sh8FgED-0ppFb2F0H7SxFtpU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});